<?php
require_once __DIR__ . '/../includes/session.php';
requireAdmin();
$pageTitle = 'About This System';
include __DIR__ . '/../includes/header.php';
include __DIR__ . '/../includes/admin_nav.php';
?>
<div class="about-hero mb-4"><div style="position:relative;z-index:1;"><div style="width:68px;height:68px;border-radius:50%;background:linear-gradient(135deg,var(--gold),var(--gold-dk));display:flex;align-items:center;justify-content:center;margin:0 auto 14px;font-family:var(--font-display);font-size:.95rem;font-weight:900;color:#06060e;box-shadow:var(--shadow-gold);">NBH</div><h1 style="font-family:var(--font-display);font-size:1.8rem;color:var(--white);margin-bottom:6px;">Nadelas Boarding House</h1><div style="font-size:.74rem;color:var(--gold);text-transform:uppercase;letter-spacing:.12em;margin-bottom:10px;">Online Booking & Management System v3.0</div><p style="color:var(--muted);max-width:520px;margin:0 auto;font-size:.85rem;line-height:1.75;">Full-featured management platform — rooms, reservations, payments, announcements, receipts, and analytics.</p></div></div>

<div style="display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-bottom:20px;">
<div class="card"><div class="card-header"><span class="card-title"><i class="fas fa-layer-group" style="color:var(--gold);margin-right:6px;"></i>Technology Stack</span></div><div class="card-body"><?php foreach([['fab fa-php','PHP 8.x','Backend'],['fas fa-database','PostgreSQL 15','Database (schema: bh)'],['fab fa-js','JavaScript ES6+','Interactivity + Charts'],['fas fa-lock','BCrypt + PDO','Security'],['fas fa-qrcode','GCash QR','Payments'],['fas fa-shield-alt','CSRF + XSS','Input protection']] as [$i,$n,$d]): ?><div style="display:flex;align-items:center;gap:10px;padding:8px 0;border-bottom:1px solid rgba(255,255,255,.04);"><div style="width:30px;height:30px;border-radius:var(--r-md);background:rgba(201,168,76,.1);display:flex;align-items:center;justify-content:center;color:var(--gold);font-size:.85rem;"><i class="<?= $i ?>"></i></div><div><div style="font-weight:600;color:var(--white);font-size:.82rem;"><?= $n ?></div><div style="font-size:.7rem;color:var(--muted);"><?= $d ?></div></div></div><?php endforeach; ?></div></div>
<div class="card"><div class="card-header"><span class="card-title"><i class="fas fa-database" style="color:var(--gold);margin-right:6px;"></i>Advanced DB Features</span></div><div class="card-body"><?php foreach([['fa-table','Schema: bh','7 normalized tables'],['fa-eye','Views','v_overdue_tenants'],['fa-cogs','PL/pgSQL Function','auto_vacate_overdue_tenants()'],['fa-bolt','10+ Indexes','Performance optimized'],['fa-exchange-alt','Transactions','Atomic operations'],['fa-check-double','DB Constraints','CHECK, UNIQUE, FK cascades']] as [$i,$n,$d]): ?><div style="display:flex;align-items:center;gap:10px;padding:8px 0;border-bottom:1px solid rgba(255,255,255,.04);"><div style="width:30px;height:30px;border-radius:var(--r-md);background:rgba(56,189,248,.08);display:flex;align-items:center;justify-content:center;color:var(--info);font-size:.82rem;"><i class="fas <?= $i ?>"></i></div><div><div style="font-weight:600;color:var(--white);font-size:.82rem;"><?= $n ?></div><div style="font-size:.7rem;color:var(--muted);"><?= $d ?></div></div></div><?php endforeach; ?></div></div>
</div>

<div class="card"><div class="card-header"><span class="card-title"><i class="fas fa-user-astronaut" style="color:var(--gold);margin-right:6px;"></i>System Developer</span></div><div class="card-body" style="display:grid;grid-template-columns:auto 1fr;gap:24px;align-items:start;">
<div style="text-align:center;"><div class="dev-avatar-default" style="width:84px;height:84px;font-size:1.5rem;">CD</div><div style="font-family:var(--font-display);font-size:1rem;color:var(--white);margin-top:10px;">Cris Danoy</div><div style="font-size:.72rem;color:var(--gold);">Full-Stack Developer</div></div>
<div><p style="color:var(--muted);font-size:.84rem;line-height:1.72;margin-bottom:14px;">Designed and built the entire Nadelas Boarding House Management System — database architecture, PHP backend, CSS/JS frontend, GCash integration, and all security layers.</p><div style="display:flex;flex-wrap:wrap;gap:9px;margin-bottom:14px;"><?php foreach([['fa-phone','09633951825','tel:09633951825'],['fa-envelope','crisdanoy9@gmail.com','mailto:crisdanoy9@gmail.com'],['fab fa-facebook','Facebook','https://www.facebook.com/cris.danoy.7/']] as [$i,$l,$h]): ?><a href="<?= $h ?>" target="_blank" class="tech-badge"><i class="<?= $i ?>"></i> <?= $l ?></a><?php endforeach; ?></div><div style="display:flex;flex-wrap:wrap;gap:7px;"><?php foreach(['PHP 8','PostgreSQL 15','HTML5','CSS3','JS ES6','Chart.js','PDO','BCrypt','GCash API'] as $t): ?><span class="tech-badge"><?= $t ?></span><?php endforeach; ?></div></div>
</div></div>

<div style="text-align:center;margin-top:20px;font-size:.74rem;color:var(--muted);">© <?= date('Y') ?> Nadelas Boarding House · Developed by Cris Danoy · Version 3.0</div>
</main></div>
<?php include __DIR__ . '/../includes/footer.php'; ?>
