<?php require_once __DIR__.'/../includes/session.php'; requireLogin(); $pageTitle='About This System'; include __DIR__.'/../includes/header.php'; include __DIR__.'/../includes/tenant_nav.php'; ?>
<div style="max-width:860px;">
<div class="about-hero"><div style="position:relative;z-index:1;"><div style="width:66px;height:66px;border-radius:50%;background:linear-gradient(135deg,var(--gold),var(--gold-dk));display:flex;align-items:center;justify-content:center;margin:0 auto 14px;font-family:var(--font-display);font-size:.92rem;font-weight:900;color:#06060e;box-shadow:var(--shadow-gold);">NBH</div><h1 style="font-family:var(--font-display);font-size:1.7rem;color:var(--white);margin-bottom:6px;">Nadelas Boarding House</h1><div style="font-size:.72rem;color:var(--gold);text-transform:uppercase;letter-spacing:.12em;margin-bottom:10px;">Online Booking & Management System v3.0</div><p style="color:var(--muted);max-width:500px;margin:0 auto;font-size:.86rem;line-height:1.75;">Modern, secure boarding house platform — online reservation, GCash payments, receipts, and announcements in one place.</p></div></div>
<div class="card mb-4"><div class="card-header"><span class="card-title"><i class="fas fa-star" style="color:var(--gold);margin-right:7px;"></i>System Features</span></div><div class="card-body"><div style="display:grid;grid-template-columns:1fr 1fr;gap:11px;"><?php foreach([['fa-bed','18 Rooms · 72 Beds · 3 Floors','GCash booking & reservation'],['fa-bullhorn','Announcements','Admin broadcasts, dismissable'],,['fa-file-invoice','Payment Receipts','Print-ready official receipts'],['fa-chart-bar','Analytics Dashboard','Occupancy & income charts'],['fa-qrcode','GCash Integration','QR payment for advance deposit'],['fa-mobile-alt','Responsive Design','Works on any device'],['fa-shield-alt','Secure System','CSRF, XSS, BCrypt protection'],['fa-gavel','House Rules','Built-in policy reference']] as [$i,$n,$d]): ?><div style="display:flex;gap:11px;align-items:flex-start;padding:10px;background:var(--surface2);border-radius:var(--r-md);"><div style="width:32px;height:32px;border-radius:var(--r-md);background:rgba(201,168,76,.12);display:flex;align-items:center;justify-content:center;color:var(--gold);flex-shrink:0;"><i class="fas <?= $i ?>"></i></div><div><div style="font-weight:600;color:var(--white);font-size:.82rem;"><?= $n ?></div><div style="font-size:.73rem;color:var(--muted);"><?= $d ?></div></div></div><?php endforeach; ?></div></div></div>
<div class="card"><div class="card-header"><span class="card-title"><i class="fas fa-laptop-code" style="color:var(--gold);margin-right:7px;"></i>Developer</span></div><div class="card-body" style="text-align:center;padding:28px;"><div class="dev-avatar-default" style="width:76px;height:76px;font-size:1.35rem;margin-bottom:12px;">CD</div><div style="font-family:var(--font-display);font-size:1.2rem;color:var(--white);margin-bottom:4px;">Cris Danoy</div><div style="font-size:.78rem;color:var(--gold);margin-bottom:12px;">Full-Stack Developer · System Architect</div><p style="color:var(--muted);font-size:.83rem;max-width:400px;margin:0 auto 18px;line-height:1.72;">Designed and built the complete Nadelas BH Management System from scratch.</p><div style="display:flex;justify-content:center;gap:10px;flex-wrap:wrap;"><?php foreach([['fa-phone','09633951825','tel:09633951825'],['fa-envelope','crisdanoy9@gmail.com','mailto:crisdanoy9@gmail.com'],['fab fa-facebook','Facebook','https://www.facebook.com/cris.danoy.7/']] as [$i,$l,$h]): ?><a href="<?= $h ?>" target="_blank" class="btn btn-ghost btn-sm"><i class="<?= $i ?>"></i> <?= $l ?></a><?php endforeach; ?></div></div></div>
<div style="text-align:center;margin-top:18px;font-size:.74rem;color:var(--muted);">© <?= date('Y') ?> Nadelas Boarding House · Version 3.0</div>
</div>
</div>
<?php include __DIR__.'/../includes/footer.php'; ?>
