<?php require_once __DIR__.'/../includes/session.php'; requireLogin(); $pageTitle='House Rules'; include __DIR__.'/../includes/header.php'; include __DIR__.'/../includes/tenant_nav.php'; ?>
<div style="max-width:880px;"><div style="text-align:center;margin-bottom:28px;"><span style="display:inline-flex;align-items:center;gap:7px;padding:5px 16px;border-radius:99px;background:rgba(201,168,76,.1);border:1px solid rgba(201,168,76,.25);font-size:.72rem;font-weight:700;color:var(--gold);text-transform:uppercase;letter-spacing:.1em;margin-bottom:12px;"><i class="fas fa-gavel"></i> House Policies</span><h1 style="font-family:var(--font-display);font-size:1.9rem;color:var(--white);margin-bottom:8px;">Rules & Regulations</h1><p style="color:var(--muted);">All tenants must follow these rules. Violations may result in eviction.</p></div>
<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:16px;margin-bottom:22px;">
<?php foreach([['01','Payment Policy','peso-sign',['Monthly rent ₱1,300 due on the 1st of every month','₱1,300 advance deposit required upon approval','Cash or GCash (09633951825) accepted','3 months unpaid = automatic eviction','Late penalties after the 5th of the month']],['02','Curfew & Visitors','clock',['Curfew at 10:00 PM — all must be inside','Visitors allowed until 8:00 PM only','Overnight visitors strictly prohibited','Visitors must sign in at entrance','Tenants responsible for visitors']],['03','Cleanliness & Noise','broom',['Keep rooms and shared areas clean','Garbage in designated bins only','No loud music after 9:00 PM','Clean shared bathrooms after use','No food inside rooms (pests)']],['04','Prohibited','ban',['No smoking/vaping inside building','No alcohol in rooms','No illegal drugs or weapons','No pets allowed','No cooking appliances in rooms']],['05','Security & Property','shield-alt',['Responsible for your own valuables','Don\'t share keys with outsiders','Report damage immediately','Willful damage charged to tenant','Lock your room when leaving']],['06','Check-Out','door-open',['15-day advance notice required','Leave room clean','Settle all balances first','Return keys to admin','Advance deposit is non-refundable']]] as [$n,$t,$i,$items]): ?>
<div class="rule-card-tenant"><div class="rule-card-header"><div class="rule-num"><?= $n ?></div><div style="font-family:var(--font-display);color:var(--white);font-size:.93rem;"><?= $t ?></div></div><ul class="rule-list"><?php foreach($items as $item): ?><li><i class="fas fa-diamond"></i><?= $item ?></li><?php endforeach; ?></ul></div>
<?php endforeach; ?>
</div>
<div style="background:rgba(240,82,82,.06);border:1px solid rgba(240,82,82,.18);border-radius:var(--r-lg);padding:14px 20px;text-align:center;margin-bottom:14px;"><i class="fas fa-exclamation-triangle" style="color:var(--danger);margin-right:7px;"></i><span style="font-size:.84rem;color:var(--muted);">Violation may result in <strong style="color:var(--danger);">immediate eviction</strong> without refund.</span></div>
<div style="background:rgba(201,168,76,.06);border:1px solid rgba(201,168,76,.18);border-radius:var(--r-lg);padding:14px 20px;text-align:center;"><span style="font-size:.82rem;color:var(--muted);">Questions? <a href="tel:09633951825" style="color:var(--gold);">09633951825</a> or <a href="https://www.facebook.com/cris.danoy.7/" target="_blank" style="color:var(--gold);"><i class="fab fa-facebook"></i> Facebook</a></span></div>
</div>
</div>
<?php include __DIR__.'/../includes/footer.php'; ?>
